# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8018ada832199957c4480536241674745a77a85d8fb6cecd99b1f744234ee3613c11af8fb7abbd03223b8177b3f5a79fc6d6475e73ed3a6d8538b4b422f2bec

test:
  secret_key_base: ecb0a8196f2c85e20b7f9d2d0ad88db0b1730d682c163f2e9972290e2f0dc0109f875d65cee569edd4bd33fa93fc5d70f824269e86875520bffa10583eaf9c55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
